name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # Nécessaire pour configure-pages
  pages: write           # Pour déployer sur Pages
  contents: read         # Pour checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère ton code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Génère ton sitemap + désactive Jekyll
      - name: Generate sitemap.xml
        run: |
          cat > sitemap.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://siphonium.github.io/fr/</loc>
              <lastmod>$(date +%F)</lastmod>
              <priority>1.00</priority>
              <changefreq>daily</changefreq>
            </url>
            <url>
              <loc>https://siphonium.github.io/fr/shop/</loc>
              <lastmod>$(date +%F)</lastmod>
              <priority>0.80</priority>
              <changefreq>weekly</changefreq>
            </url>
            <!-- Ajoute ici tes autres URLs -->
          </urlset>
          EOF
          touch .nojekyll

      # 3. Prépare l’ID token pour Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 4. Emballe tout dans l’artifact "github-pages"
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # déploie tout ce qui est à la racine

      # 5. Déploie l’artifact sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
