name: Auto-generate sitemap.xml and deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create sitemap.xml dynamically
      run: |
        mkdir -p _site

        echo '<?xml version="1.0" encoding="UTF-8"?>' > _site/sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> _site/sitemap.xml

        echo '<url><loc>https://siphonium.github.io/</loc><lastmod>2025-07-24</lastmod><changefreq>monthly</changefreq><priority>1.0</priority></url>' >> _site/sitemap.xml
        echo '<url><loc>https://siphonium.github.io/fr/</loc><changefreq>weekly</changefreq></url>' >> _site/sitemap.xml
        echo '<url><loc>https://siphonium.github.io/fr/shop</loc><lastmod>2025-07-24</lastmod><changefreq>weekly</changefreq></url>' >> _site/sitemap.xml
        echo '<url><loc>https://siphonium.github.io/fr/launcher</loc><lastmod>2025-07-24</lastmod><priority>0.5</priority></url>' >> _site/sitemap.xml
        echo '<url><loc>https://siphonium.github.io/fr/credit</loc><lastmod>2025-07-24</lastmod></url>' >> _site/sitemap.xml

        echo '</urlset>' >> _site/sitemap.xml

    - name: Fix MIME type with .htaccess
      run: echo 'AddType application/xml .xml' > _site/.htaccess

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
